### ISSUE TITLE
Firehose exporter crashes due to `concurrent map iteration and map write`

### ISSUE THREAD

**Issue by irfanhabib** [cloudfoundry-community/firehose_exporter#17]
I've deployed this against my Cloud Foundry instance using the latest `cfcommunity/firehose-exporter` docker image. I can see data coming through in Grafana, however after a few hours it tends to crash with the following stack trace:

```
ime="2017-07-11T08:32:03Z" level=info msg="Starting firehose_exporter (version=4.2.1, branch=HEAD, revision=97f51ecad6d51ecd5279aa263ac462c0ab0c78f1)" source="firehose_exporter.go:250" 
time="2017-07-11T08:32:03Z" level=info msg="Build context (go=go1.8.3, user=root@9c6c91fc16d7, date=20170707-09:27:39)" source="firehose_exporter.go:251" 
time="2017-07-11T08:32:03Z" level=info msg="Starting Firehose Nozzle..." source="firehose_nozzle.go:58" 
time="2017-07-11T08:32:03Z" level=info msg="Listening on :9186" source="firehose_exporter.go:327" 
fatal error: concurrent map iteration and map write

goroutine 12120 [running]:
runtime.throw(0x8f7a6a, 0x26)
        /usr/local/go/src/runtime/panic.go:596 +0x95 fp=0xc4204e6ca0 sp=0xc4204e6c80
runtime.mapiternext(0xc4204e6dc8)
        /usr/local/go/src/runtime/hashmap.go:737 +0x7ee fp=0xc4204e6d50 sp=0xc4204e6ca0
github.com/cloudfoundry-community/firehose_exporter/metrics.(*Store).GetValueMetrics(0xc42009eb90, 0x404300, 0xc420415cc8, 0xc420415cd0)
        /go/src/github.com/cloudfoundry-community/firehose_exporter/metrics/store.go:214 +0x130 fp=0xc4204e6e38 sp=0xc4204e6d50
github.com/cloudfoundry-community/firehose_exporter/collectors.ValueMetricsCollector.Collect(0x8e82c2, 0x8, 0x0, 0x0, 0xc42009eb90, 0xc420143110, 0xc420789e60)
        /go/src/github.com/cloudfoundry-community/firehose_exporter/collectors/value_metrics_collector.go:40 +0x43 fp=0xc4204e6f50 sp=0xc4204e6e38
github.com/cloudfoundry-community/firehose_exporter/collectors.(*ValueMetricsCollector).Collect(0xc420164a50, 0xc420789e60)
        <autogenerated>:9 +0x66 fp=0xc4204e6f98 sp=0xc4204e6f50
github.com/cloudfoundry-community/firehose_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func2(0xc4202df330, 0xc420789e60, 0xb0c240, 0xc420164a50)
        /go/src/github.com/cloudfoundry-community/firehose_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:382 +0x61 fp=0xc4204e6fc0 sp=0xc4204e6f98
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc4204e6fc8 sp=0xc4204e6fc0
created by github.com/cloudfoundry-community/firehose_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather
        /go/src/github.com/cloudfoundry-community/firehose_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:383 +0x2ec

goroutine 1 [IO wait]:
net.runtime_pollWait(0x7f0de74cc168, 0x72, 0x0)
        /usr/local/go/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc420143418, 0x72, 0x0, 0xc420201a00)
        /usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc420143418, 0xffffffffffffffff, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).accept(0xc4201433b0, 0x0, 0xb09ec0, 0xc420201a00)
        /usr/local/go/src/net/fd_unix.go:430 +0x1e5
net.(*TCPListener).accept(0xc42007e300, 0xc42017bac0, 0x859d40, 0xffffffffffffffff)
        /usr/local/go/src/net/tcpsock_posix.go:136 +0x2e
net.(*TCPListener).AcceptTCP(0xc42007e300, 0xc420049be8, 0xc420049bf0, 0xc420049be0)
        /usr/local/go/src/net/tcpsock.go:215 +0x49
net/http.tcpKeepAliveListener.Accept(0xc42007e300, 0x904640, 0xc42017ba40, 0xb0fd80, 0xc4201655f0)
        /usr/local/go/src/net/http/server.go:3044 +0x2f
net/http.(*Server).Serve(0xc4200bb4a0, 0xb0f700, 0xc42007e300, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:2643 +0x228
net/http.(*Server).ListenAndServe(0xc4200bb4a0, 0xc4200bb4a0, 0x2)
        /usr/local/go/src/net/http/server.go:2585 +0xb0
net/http.ListenAndServe(0x8e707f, 0x5, 0x0, 0x0, 0xc42009eb90, 0xc420164a50)
        /usr/local/go/src/net/http/server.go:2787 +0x7f
main.main()
        /go/src/github.com/cloudfoundry-community/firehose_exporter/firehose_exporter.go:328 +0xae8

goroutine 21 [select, 1 minutes]:
github.com/cloudfoundry-community/firehose_exporter/vendor/github.com/patrickmn/go-cache.(*janitor).Run(0xc42013e2f0, 0xc42013c7c0)
        /go/src/github.com/cloudfoundry-community/firehose_exporter/vendor/github.com/patrickmn/go-cache/cache.go:1037 +0x171
created by github.com/cloudfoundry-community/firehose_exporter/vendor/github.com/patrickmn/go-cache.runJanitor
        /go/src/github.com/cloudfoundry-community/firehose_exporter/vendor/github.com/patrickmn/go-cache/cache.go:1056 +0x8d
goroutine 21 [select, 1 minutes]:
github.com/cloudfoundry-community/firehose_exporter/vendor/github.com/patrickmn/go-cache.(*janitor).Run(0xc42013e2f0, 0xc42013c7c0)
        /go/src/github.com/cloudfoundry-community/firehose_exporter/vendor/github.com/patrickmn/go-cache/cache.go:1037 +0x171
created by github.com/cloudfoundry-community/firehose_exporter/vendor/github.com/patrickmn/go-cache.runJanitor
        /go/src/github.com/cloudfoundry-community/firehose_exporter/vendor/github.com/patrickmn/go-cache/cache.go:1056 +0x8d

goroutine 22 [select, 1 minutes]:
github.com/cloudfoundry-community/firehose_exporter/vendor/github.com/patrickmn/go-cache.(*janitor).Run(0xc42013e300, 0xc42013c800)
        /go/src/github.com/cloudfoundry-community/firehose_exporter/vendor/github.com/patrickmn/go-cache/cache.go:1037 +0x171
created by github.com/cloudfoundry-community/firehose_exporter/vendor/github.com/patrickmn/go-cache.runJanitor
        /go/src/github.com/cloudfoundry-community/firehose_exporter/vendor/github.com/patrickmn/go-cache/cache.go:1056 +0x8d

goroutine 23 [select, 1 minutes]:
github.com/cloudfoundry-community/firehose_exporter/vendor/github.com/patrickmn/go-cache.(*janitor).Run(0xc42013e310, 0xc42013c840)
        /go/src/github.com/cloudfoundry-community/firehose_exporter/vendor/github.com/patrickmn/go-cache/cache.go:1037 +0x171
created by github.com/cloudfoundry-community/firehose_exporter/vendor/github.com/patrickmn/go-cache.runJanitor
        /go/src/github.com/cloudfoundry-community/firehose_exporter/vendor/github.com/patrickmn/go-cache/cache.go:1056 +0x8d

goroutine 24 [select, 1 minutes]:
github.com/cloudfoundry-community/firehose_exporter/vendor/github.com/patrickmn/go-cache.(*janitor).Run(0xc42013e320, 0xc42013c880)
        /go/src/github.com/cloudfoundry-community/firehose_exporter/vendor/github.com/patrickmn/go-cache/cache.go:1037 +0x171
created by github.com/cloudfoundry-community/firehose_exporter/vendor/github.com/patrickmn/go-cache.runJanitor
        /go/src/github.com/cloudfoundry-community/firehose_exporter/vendor/github.com/patrickmn/go-cache/cache.go:1056 +0x8d

goroutine 25 [select, 1 minutes]:
github.com/cloudfoundry-community/firehose_exporter/vendor/github.com/patrickmn/go-cache.(*janitor).Run(0xc42013e330, 0xc42013c8c0)
        /go/src/github.com/cloudfoundry-community/firehose_exporter/vendor/github.com/patrickmn/go-cache/cache.go:1037 +0x171
created by github.com/cloudfoundry-community/firehose_exporter/vendor/github.com/patrickmn/go-cache.runJanitor
        /go/src/github.com/cloudfoundry-community/firehose_exporter/vendor/github.com/patrickmn/go-cache/cache.go:1056 +0x8d

goroutine 26 [select]:
github.com/cloudfoundry-community/firehose_exporter/firehosenozzle.(*FirehoseNozzle).parseEnvelopes(0xc420084900, 0x1, 0x1)
        /go/src/github.com/cloudfoundry-community/firehose_exporter/firehosenozzle/firehose_nozzle.go:90 +0x1ad
github.com/cloudfoundry-community/firehose_exporter/firehosenozzle.(*FirehoseNozzle).Start(0xc420084900, 0x0, 0x0)
        /go/src/github.com/cloudfoundry-community/firehose_exporter/firehosenozzle/firehose_nozzle.go:60 +0xb8
main.main.func1(0xc420084900)
        /go/src/github.com/cloudfoundry-community/firehose_exporter/firehose_exporter.go:294 +0x2b
created by main.main
        /go/src/github.com/cloudfoundry-community/firehose_exporter/firehose_exporter.go:295 +0x5f0

goroutine 33 [runnable]:
github.com/cloudfoundry-community/firehose_exporter/vendor/github.com/cloudfoundry/noaa/consumer.(*Consumer).firehose.func1(0xc42041b7a0)
        /go/src/github.com/cloudfoundry-community/firehose_exporter/vendor/github.com/cloudfoundry/noaa/consumer/async.go:232 +0x4a
github.com/cloudfoundry-community/firehose_exporter/vendor/github.com/cloudfoundry/noaa/consumer.(*Consumer).listenForMessages(0xc420172240, 0xc420148120, 0xc420150130, 0x0, 0x0)
        /go/src/github.com/cloudfoundry-community/firehose_exporter/vendor/github.com/cloudfoundry/noaa/consumer/async.go:280 +0x247
github.com/cloudfoundry-community/firehose_exporter/vendor/github.com/cloudfoundry/noaa/consumer.(*Consumer).listenAction.func1(0xc420172240, 0xc420148160, 0xc420172240)
        /go/src/github.com/cloudfoundry-community/firehose_exporter/vendor/github.com/cloudfoundry/noaa/consumer/async.go:294 +0x11d
github.com/cloudfoundry-community/firehose_exporter/vendor/github.com/cloudfoundry/noaa/consumer.(*Consumer).retryAction(0xc420172240, 0xc42014a140, 0xc4201442a0)
        /go/src/github.com/cloudfoundry-community/firehose_exporter/vendor/github.com/cloudfoundry/noaa/consumer/async.go:316 +0x141
github.com/cloudfoundry-community/firehose_exporter/vendor/github.com/cloudfoundry/noaa/consumer.(*Consumer).firehose.func2(0xc4201442a0, 0xc420144240, 0xc4201700c0, 0xc420172240, 0xc420148120, 0xc420150130)
        /go/src/github.com/cloudfoundry-community/firehose_exporter/vendor/github.com/cloudfoundry/noaa/consumer/async.go:240 +0x177
created by github.com/cloudfoundry-community/firehose_exporter/vendor/github.com/cloudfoundry/noaa/consumer.(*Consumer).firehose
        /go/src/github.com/cloudfoundry-community/firehose_exporter/vendor/github.com/cloudfoundry/noaa/consumer/async.go:245 +0x10a
goroutine 12107 [chan receive]:
github.com/cloudfoundry-community/firehose_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather(0xc4200a8480, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/cloudfoundry-community/firehose_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:404 +0x4fe
github.com/cloudfoundry-community/firehose_exporter/vendor/github.com/prometheus/client_golang/prometheus.UninstrumentedHandler.func1(0xb0edc0, 0xc42007e660, 0xc4200ec300)
        /go/src/github.com/cloudfoundry-community/firehose_exporter/vendor/github.com/prometheus/client_golang/prometheus/http.go:76 +0x47
net/http.HandlerFunc.ServeHTTP(0x904418, 0xb0edc0, 0xc42007e660, 0xc4200ec300)
        /usr/local/go/src/net/http/server.go:1942 +0x44
net/http.(Handler).ServeHTTP-fm(0xb0edc0, 0xc42007e660, 0xc4200ec300)
        /go/src/github.com/cloudfoundry-community/firehose_exporter/firehose_exporter.go:232 +0x4d
github.com/cloudfoundry-community/firehose_exporter/vendor/github.com/prometheus/client_golang/prometheus.InstrumentHandlerFuncWithOpts.func1(0xb0f300, 0xc420102000, 0xc4200ec300)
        /go/src/github.com/cloudfoundry-community/firehose_exporter/vendor/github.com/prometheus/client_golang/prometheus/http.go:307 +0x224
net/http.HandlerFunc.ServeHTTP(0xc42009f2c0, 0xb0f300, 0xc420102000, 0xc4200ec300)
        /usr/local/go/src/net/http/server.go:1942 +0x44
net/http.(*ServeMux).ServeHTTP(0xb423e0, 0xb0f300, 0xc420102000, 0xc4200ec300)
        /usr/local/go/src/net/http/server.go:2238 +0x130
net/http.serverHandler.ServeHTTP(0xc4200bb4a0, 0xb0f300, 0xc420102000, 0xc4200ec300)
        /usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc42017ba40, 0xb0fcc0, 0xc420272300)
        /usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2668 +0x2ce

goroutine 12108 [IO wait]:
net.runtime_pollWait(0x7f0de74cbf28, 0x72, 0x7)
        /usr/local/go/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc4205d3798, 0x72, 0xb0b380, 0xb073b0)
        /usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc4205d3798, 0xc420272351, 0x1)
        /usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).Read(0xc4205d3730, 0xc420272351, 0x1, 0x1, 0x0, 0xb0b380, 0xb073b0)
        /usr/local/go/src/net/fd_unix.go:250 +0x1b7
net.(*conn).Read(0xc42007e658, 0xc420272351, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:181 +0x70
net/http.(*connReader).backgroundRead(0xc420272340)
        /usr/local/go/src/net/http/server.go:656 +0x58
created by net/http.(*connReader).startBackgroundRead
        /usr/local/go/src/net/http/server.go:652 +0xdf
goroutine 12111 [runnable]:
os.(*File).Read(0xc420604008, 0xc4207d9000, 0x1000, 0x1000, 0x2000, 0x2000, 0x0)
        /usr/local/go/src/os/file.go:97 +0x318
bufio.(*Scanner).Scan(0xc4205b1a00, 0x5)
        /usr/local/go/src/bufio/scan.go:207 +0x294
github.com/cloudfoundry-community/firehose_exporter/vendor/github.com/prometheus/procfs.FS.NewStat(0x8e7070, 0x5, 0x0, 0x0, 0x0)
        /go/src/github.com/cloudfoundry-community/firehose_exporter/vendor/github.com/prometheus/procfs/stat.go:35 +0x131
github.com/cloudfoundry-community/firehose_exporter/vendor/github.com/prometheus/procfs.ProcStat.StartTime(0x1, 0xc420662010, 0xf, 0xc420662020, 0x1, 0x0, 0x1, 0x1, 0x0, 0xffffffffffffffff, ...)
        /go/src/github.com/cloudfoundry-community/firehose_exporter/vendor/github.com/prometheus/procfs/proc_stat.go:165 +0x3f
github.com/cloudfoundry-community/firehose_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*processCollector).processCollect(0xc42009e320, 0xc420789e60)
        /go/src/github.com/cloudfoundry-community/firehose_exporter/vendor/github.com/prometheus/client_golang/prometheus/process_collector.go:128 +0x55e
github.com/cloudfoundry-community/firehose_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*processCollector).(github.com/cloudfoundry-community/firehose_exporter/vendor/github.com/prometheus/cl
ient_golang/prometheus.processCollect)-fm(0xc420789e60)
        /go/src/github.com/cloudfoundry-community/firehose_exporter/vendor/github.com/prometheus/client_golang/prometheus/process_collector.go:90 +0x34
github.com/cloudfoundry-community/firehose_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*processCollector).Collect(0xc42009e320, 0xc420789e60)
        /go/src/github.com/cloudfoundry-community/firehose_exporter/vendor/github.com/prometheus/client_golang/prometheus/process_collector.go:108 +0x34
github.com/cloudfoundry-community/firehose_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func2(0xc4202df330, 0xc420789e60, 0xb0c500, 0xc42009e320)
        /go/src/github.com/cloudfoundry-community/firehose_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:382 +0x61
created by github.com/cloudfoundry-community/firehose_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather
        /go/src/github.com/cloudfoundry-community/firehose_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:383 +0x2ec
```

**Comment by irfanhabib** [comment]
The explicit throw in the first goroutine is the following exception

`concurrent map iteration and map write` in hashmap.go

**Comment by yatzek** [comment]
Same here:

fatal error: concurrent map iteration and map write

goroutine 5241 [running]:
runtime.throw(0x8f7a6a, 0x26)
        /usr/local/go/src/runtime/panic.go:596 +0x95 fp=0xc420d38c28 sp=0xc420d38c08
runtime.mapiternext(0xc420d38d50)
        /usr/local/go/src/runtime/hashmap.go:737 +0x7ee fp=0xc420d38cd8 sp=0xc420d38c28
github.com/cloudfoundry-community/firehose_exporter/metrics.(*Store).GetCounterEvents(0xc420094aa0, 0xc4211636f0, 0x48, 0
xffffffffffffffff)
        /go/src/github.com/cloudfoundry-community/firehose_exporter/metrics/store.go:186 +0x130 fp=0xc420d38dc0 sp=0xc420
d38cd8
github.com/cloudfoundry-community/firehose_exporter/collectors.CounterEventsCollector.Collect(0x8e82c2, 0x8, 0x7fff0bbfce
3a, 0x3, 0xc420094aa0, 0xc420128af0, 0xc4201688a0)
        /go/src/github.com/cloudfoundry-community/firehose_exporter/collectors/counter_events_collector.go:40 +0x43 fp=0x
c420d38f50 sp=0xc420d38dc0
github.com/cloudfoundry-community/firehose_exporter/collectors.(*CounterEventsCollector).Collect(0xc42012c5d0, 0xc4201688
a0)
        <autogenerated>:3 +0x66 fp=0xc420d38f98 sp=0xc420d38f50
github.com/cloudfoundry-community/firehose_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gat
her.func2(0xc420bb1e70, 0xc4201688a0, 0xb0c180, 0xc42012c5d0)
        /go/src/github.com/cloudfoundry-community/firehose_exporter/vendor/github.com/prometheus/client_golang/prometheus
/registry.go:382 +0x61 fp=0xc420d38fc0 sp=0xc420d38f98
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc420d38fc8 sp=0xc420d38fc0
created by github.com/cloudfoundry-community/firehose_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*Re
gistry).Gather
        /go/src/github.com/cloudfoundry-community/firehose_exporter/vendor/github.com/prometheus/client_golang/prometheus
/registry.go:383 +0x2ec

**Comment by frodenas** [comment]
Can you please try using the new [v4.2.3](https://github.com/cloudfoundry-community/firehose_exporter/releases/tag/v4.2.3) release?

This is really hard to reproduce (I've not seen it on my deployments), but I suspect this is related to a new check in go 1.8 and the way the [go-cache](https://github.com/patrickmn/go-cache) library was returning the cached items. I've updated the vendored `go-cache` library with the latest version as it contains a [commit](https://github.com/patrickmn/go-cache/commit/a2d8b56f0c21c5562c23717b6137ed6254ddc6d4#diff-56ffa6659747ba7a23d2b5597a4cda5d) that might fix this.
